###########################################################
# Makefile for CS530 Assignment #1 
# Tom Nguyen and Kellen Gillooley
# Kellen Gillooley: CSSC1024@edoras.sdsu.edu
# Tom Nguyen: CSSC0883@edoras.sdsu.edu
# February 11, 2017
###########################################################

xsd: proj1.c
	gcc -o xsd proj1.c

	
clean:
	rm -f xsd

####################[ EDO: Makefile ]######################