# David Arce: cssc0858@edoras.sdsu.edu (820099092)
# Kellen Gillooley: cssc1024@edoras.sdsu.edu (818216237)
# Logan Lasiter: cssc1034@edoras.sdsu.edu (820065721)
# Tom Nguyen: cssc0883@edoras.sdsu.edu (820468110)

# CS 530 Spring 2017

# Assignment #2, XE Disassembler 'dasm'
# Makefile

dasm: dasm.c header.h
	gcc -o dasm dasm.c header.h

